### ISSUE TITLE
Add map to anchor links at the top of the page

### ISSUE THREAD

**Issue by notexactlyawe** [CreatEDHack/2018#23]
![screenshot from 2018-03-04 09-56-39](https://user-images.githubusercontent.com/4598381/36944361-5db5e692-1f92-11e8-93be-e5cc78ae48bf.png)

Have a "MAP" link in these since it's also a section. The wording could be different if thought appropriate.

**Comment by prototriangle** [comment]
Would "VENUE" be alright?

**Comment by notexactlyawe** [comment]
That would be even better
